package com.pathboot.dto;

import com.pathboot.enums.DomainType;
import com.pathboot.enums.Language;

/**
 * Immutable data-transfer object carrying all fields required to build a
 * {@link com.pathboot.model.UserInteraction} entity.
 *
 * <p>Used as the source object for the MapStruct {@link com.pathboot.mapper.UserInteractionMapper},
 * keeping the facade service free from manual entity construction code.</p>
 *
 * <p>Defined as a Java {@code record} so the compiler generates an all-args constructor,
 * accessors, {@code equals}, {@code hashCode}, and {@code toString} for free.</p>
 */
public record UserInteractionDto(

        /** Client-supplied or server-generated session identifier. */
        String sessionId,

        /** The raw text as the user submitted it (Amharic, Norwegian, or English). */
        String originalInput,

        /** Language detected in the original input. */
        Language detectedLanguage,

        /**
         * English translation of the original input.
         * {@code null} when the input was already English.
         */
        String translatedInput,

        /** Domain classified from the (translated) English question. */
        DomainType detectedDomain,

        /** English text generated by the domain agent. */
        String generatedResponseEnglish,

        /** Final response delivered to the user (may be translated back). */
        String finalResponse
) {}

