package com.pathboot.model;

import com.pathboot.enums.DomainType;
import com.pathboot.enums.Language;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * JPA entity that persists every user interaction (question + response) to the SQLite database.
 *
 * <p>Stored for audit, analysis, and future fine-tuning purposes.</p>
 */
@Entity
@Table(name = "user_interactions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
public class UserInteraction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /** Client-supplied or server-generated session identifier. */
    @Column(name = "session_id", nullable = false)
    private String sessionId;

    /** The raw text as the user submitted it (may be Amharic, Norwegian, or English). */
    @Column(name = "original_input", nullable = false, columnDefinition = "TEXT")
    private String originalInput;

    /** Language detected in the original input. */
    @Enumerated(EnumType.STRING)
    @Column(name = "detected_language", nullable = false)
    private Language detectedLanguage;

    /** English translation of the original input (null when input was already English). */
    @Column(name = "translated_input", columnDefinition = "TEXT")
    private String translatedInput;

    /** Domain classified from the (translated) English question. */
    @Enumerated(EnumType.STRING)
    @Column(name = "detected_domain", nullable = false)
    private DomainType detectedDomain;

    /** English text generated by the domain agent. */
    @Column(name = "generated_response_english", nullable = false, columnDefinition = "TEXT")
    private String generatedResponseEnglish;

    /** Final response delivered to the user (translated back to original language when needed). */
    @Column(name = "final_response", nullable = false, columnDefinition = "TEXT")
    private String finalResponse;

    /** Timestamp when the interaction was recorded. */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}

