package com.pathboot.mapper;

import com.pathboot.dto.UserInteractionDto;
import com.pathboot.model.UserInteraction;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * MapStruct mapper that converts a {@link UserInteractionDto} into a
 * {@link UserInteraction} JPA entity.
 *
 * <p>{@code componentModel = "spring"} tells MapStruct to generate a Spring
 * {@code @Component} so the mapper can be injected anywhere via constructor DI.</p>
 *
 * <p>The {@code id} and {@code createdAt} fields are intentionally ignored:
 * {@code id} is auto-generated by Hibernate, and {@code createdAt} is set by
 * {@code @CreationTimestamp}.</p>
 */
@Mapper(componentModel = "spring")
public interface UserInteractionMapper {

    /**
     * Maps all matching fields from {@link UserInteractionDto} to {@link UserInteraction}.
     *
     * @param dto the source data-transfer object
     * @return a fully populated {@link UserInteraction} entity (without {@code id}/{@code createdAt})
     */
    @Mapping(target = "id",        ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    UserInteraction toUserInteraction(UserInteractionDto dto);
}

